#!/bin/bash

docker build -t aws_container .

echo "Entering aws-deployment"
docker run -it \
  -v ~/.aws/:/home/aws/.aws/:ro \
  -v `pwd`:/home/aws/current:ro \
  aws_container
echo "Leaving aws-deployment"
